name: ClientWorker 
catch_rules:
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com)
  transform_rules:
    - search: _
      replace:
        - _
        - https://unpkg.zhimg.com #回源已关闭，原缓存有效
        - https://npm.elemecdn.com #2022/7/12 确认关闭回源，缓存有效
        - https://code.bdstatic.com/npm #确认关闭回源，缓存有效
        - https://npm.sourcegcdn.com #滥用封仓库，强制数字版本号
        - https://cdn.bilicdn.tk/npm # 由GamerNoTitle提供的反代，请勿滥用:D
        - https://new-home-delta.vercel.app/ #部署在Vercel的站点
      - search: _ 
        action: fetch
        fetch:
          engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503
      - search: \.html$
        header:
          Content-Type: text/html;charset=UTF-8 #修复标头

name: ClientWorker Config
cleaninterval: 1000*20 # 每20秒检测并清理一次

name: ClientWorker
hotpatch:
    - https://raw.githubusercontent.com/1834423612/new-home/cw.js
    - https://cdn.jsdelivr.net/gh/1834423612/new-home@master/cw.js
    - https://new-home-delta.vercel.app/cw.js
    
name: ClientWorker
hotconfig:
    - https://raw.githubusercontent.com/1834423612/new-home/config.yaml
    - https://cdn.jsdelivr.net/gh/1834423612/new-home@master/config.yaml
    - https://new-home-delta.vercel.app/config.yaml

