-- kjch Personal Website Database Schema
-- MySQL 8

CREATE TABLE IF NOT EXISTS `projects` (
  `id` VARCHAR(100) PRIMARY KEY,
  `title_zh` VARCHAR(500) NOT NULL,
  `title_en` VARCHAR(500) NOT NULL,
  `description_zh` TEXT,
  `description_en` TEXT,
  `category` VARCHAR(50) NOT NULL DEFAULT 'website',
  `tags` JSON,
  `image` VARCHAR(1000),
  `link` VARCHAR(1000),
  `source` VARCHAR(1000),
  `date` VARCHAR(100),
  `featured` BOOLEAN DEFAULT FALSE,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `experiences` (
  `id` VARCHAR(100) PRIMARY KEY,
  `title_zh` VARCHAR(500) NOT NULL,
  `title_en` VARCHAR(500) NOT NULL,
  `org_zh` VARCHAR(500) NOT NULL,
  `org_en` VARCHAR(500) NOT NULL,
  `description_zh` TEXT,
  `description_en` TEXT,
  `start_date` VARCHAR(50),
  `end_date` VARCHAR(50),
  `icon` VARCHAR(200),
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `skills` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(200) NOT NULL,
  `icon` VARCHAR(200) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sites` (
  `id` VARCHAR(100) PRIMARY KEY,
  `title_zh` VARCHAR(500) NOT NULL,
  `title_en` VARCHAR(500) NOT NULL,
  `description_zh` TEXT,
  `description_en` TEXT,
  `url` VARCHAR(1000),
  `since` VARCHAR(50),
  `tags` JSON,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fortune_tags` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `text_zh` VARCHAR(500) NOT NULL,
  `text_en` VARCHAR(500) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `social_links` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(200) NOT NULL,
  `url` VARCHAR(1000),
  `color` VARCHAR(20),
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `site_config` (
  `key` VARCHAR(100) PRIMARY KEY,
  `value` TEXT,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
