var Language = {
  "en": {
    "老况的实验室": "Jiacheng's Laboratory",
    "Made by kjch™": "Made by kjch",
    "kjch的": "kjch's",
    "黑历史": "Black History Collection",
    "作品集": "Works Collection",
    "Project": "Project",
    "项目": "",
    "毕业设计": "Graduation Design Project",
    "“为Minecraft学校建筑制作的一个网站，用于展示三班同学的建筑成果。”": "“A website for the architecture of Minecraft School, which is used to show the architectural achievements of Class Three students.”",
    "一个简洁的站点，展示了用Minecraft还原出一个忠德学校。": "A simple site that shows how to restore ZhongDe school with Minecraft.",
    "本项目目前仍在进行中，将延续给下届同学，也是一个情感的延续。": "This project is still in progress and will be extended to the next sessions classmates, which is also an emotional continuation.",
    "2022届初三毕业生毕业回忆视频": "Video of Graduation Memories of 2022 Junior Three Graduates",
    "Video": "Video",
    "毕业纪念": "Memory of Graduation",
    "“毕业时留给同学们最后的礼物”": "“The last gift for all students when they graduated”",
    "历经多次改版制作、挑选照片，最终呈现给所有初三毕业生": "After many revisions, production and selection of photos, they were finally presented to all gread 9 graduates",
    "2019-2022 一段美好的初中时光......": "2019-2022 A good time for Middle School...",
    "“2022届的几个毕业生组成的团体，共同在Minecraft中还原了忠德学校。”": "“A group composed of several graduates of the 2022 class has jointly restored ZhongDe School in Minecraft.”",
    "正在进行中的项目，第一次在MC里建成如此大规模的建筑，也完成了我们用MC还原学校的梦想。": "The ongoing project is the first time to build such a large-scale building in MC, which also completes our dream of using MC to restore the school.",
    "地图中部分建筑仍处于建筑当中，目前更新进度极慢。": "Some buildings on the map are still under construction, and the current update progress is extremely slow.",
    "服务器地址：mc.kjchmc.cn": "Minecraft Server address: mc.kjchmc.cn",
    "游戏版本：Java 1.16.5": "Minecraft version: Java 1.16.5",
    "需下载特别制定版游戏客户端，客户端下载链接：": "It is necessary to download the specially designed game client. The client download link:",
    "下载链接(点击前往)": "Download link (click it to download)",
    "Site 站点": "Site",
    "老况的文件库": "Jiacheng files library",
    "存储库": "flies storage",
    "“一个存储着许多资料的站点”": "“A site storing many materials”",
    "网站基于 Alist。涵盖了丰富资源，包括电子课本，番剧，Bilibili录播，实用电脑软件，壁纸，网站源码": "The website is based on A-List. It covers a wealth of resources, including China electronic textbooks, dramas, Bilibili live video, practical computer software, wallpapers, and some website source code.",
    "访问网站": "Visit the website",
    "老况的小窝": "Jiacheng's blog",
    "“一个属于自己的博客”": "“A blog of my own”",
    "学习繁忙，有可能经常断更文章。": "I am busy with my studies, and I may change my articles frequently.",
    "kjch起始页": "kjch begging pages",
    "起始页": "Begging Pages",
    "设计": "Design",
    "前端": "Front end",
    "“多功能起始页”": "“Multifunctional Begging Page”",
    "内置多种壁纸以及多种可选的搜索引擎，美化了原先的浏览器内置标签页。": "A variety of built-in wallpapers and a variety of optional search engines have beautified the original built-in tabs of the browser.",
    "网站状态监控": "Site Status Monitoring",
    "status": "status",
    "服务器监控": "Servers Monitoring",
    "“网站服务器在线状态检测站点”": "“Web server online status detection site”",
    "CDN存储仓库": "CDN Storage Warehouse",
    "仓库": "Storage",
    "“小众的CDN加速服务”": "“A niche CDN acceleration service”",
    "给网站提供文件加速服务，减轻站点服务器压力。": "Provide file acceleration services for websites to reduce the pressure on site servers.",
    "无前端显示界面，仅限于网站链接调用获取所需资源文件。": "There is no front-end display interface, and only the website link call is used to obtain the required resource files.",
    "API主站点": "API main site",
    "“为网站提供基础工具功能”": "“Provide basic tool functions for websites”",
    "API主站点系统涵盖数十种维持网站正常运行的基本工具及资源。": "The API system covers dozens of basic tools and resources to maintain the normal operation of the website.",
    "无前端显示页面，仅限于网站链接调用获取所需资源文件。": "There is no front end display page. Only the website link calls can get the required resource files.",
    "老k的主页": "Jiacheng's Homepages",
    "个人网站": "Personal Website",
    "“网络世界上自己的小小一角。”": "“A small corner of the Internet world.”",
    "有一个属于自己的网站很酷，不是吗？": "It's cool to have a website of yourself, isn't it?",
    "在互联网上有属于自己的小小一角是一件很有意义的事情，我是这么认为的。": "It is very meaningful to have a small corner of your own on the Internet. I think so.",
    "Gadgets": "Gadgets",
    "小玩意和开源工具": "Gadgets and Open Source Tools",
    "免费域名": "Free Domains",
    "开源": "Open Source",
    "“为你有趣的开源项目提供免费子域名”": "“Provide free subdomains for your interesting open source projects”",
    "有一个酷酷的域名难道不是一个很有趣的事情吗?": "Isn't it interesting to have a cool domain!",
    "正如域名表达的内容一样，快来加入一起 “Make Some Cool” 吧！": "Just like the content expressed by the domain name, come and join the “Make Some Cool”!",
    "前往Github仓库": "Go to the Github repository",
    "访客计数器": "Visiter Counter",
    "“记录网站访客数并实时显示”": "“Record the number of website visitors and display them in real time”",
    "根据JS版修改并再创作而来。": "It is modified and re created according to the JS version.",
    "随机二次元图片": "Random anime Picture",
    "壁纸": "Wallpapers",
    "“随机展示一张二次元壁纸，可用作网站壁纸。”": "“Randomly display a anime wallpaper, which can be used as website wallpaper.”",
    "访问": "Visited Now!",
    "IP签名墙": "IP Signature Images",
    "“快速生成一张带有浏览器、时间、访问IP信息的一张小图片”": "“Quickly generate a small picture with your browser, time and access IP information”"
  },
  "zhCN": {
    "老况的实验室": "老况的实验室",
    "Made by kjch™": "Made by kjch™",
    "kjch的": "kjch的",
    "黑历史": "黑历史",
    "作品集": "作品集",
    "Project": "Project",
    "项目": "项目",
    "毕业设计": "毕业设计",
    "“为Minecraft学校建筑制作的一个网站，用于展示三班同学的建筑成果。”": "“为Minecraft学校建筑制作的一个网站，用于展示三班同学的建筑成果。”",
    "一个简洁的站点，展示了用Minecraft还原出一个忠德学校。": "一个简洁的站点，展示了用Minecraft还原出一个忠德学校。",
    "本项目目前仍在进行中，将延续给下届同学，也是一个情感的延续。": "本项目目前仍在进行中，将延续给下届同学，也是一个情感的延续。",
    "2022届初三毕业生毕业回忆视频": "2022届初三毕业生毕业回忆视频",
    "毕业纪念": "毕业纪念",
    "“毕业时留给同学们最后的礼物”": "“毕业时留给同学们最后的礼物”",
    "历经多次改版制作、挑选照片，最终呈现给所有初三毕业生": "历经多次改版制作、挑选照片，最终呈现给所有初三毕业生",
    "2019-2022 一段美好的初中时光......": "2019-2022 一段美好的初中时光......",
    "“2022届的几个毕业生组成的团体，共同在Minecraft中还原了忠德学校。”": "“2022届的几个毕业生组成的团体，共同在Minecraft中还原了忠德学校。”",
    "正在进行中的项目，第一次在MC里建成如此大规模的建筑，也完成了我们用MC还原学校的梦想。": "正在进行中的项目，第一次在MC里建成如此大规模的建筑，也完成了我们用MC还原学校的梦想。",
    "地图中部分建筑仍处于建筑当中，目前更新进度极慢。": "地图中部分建筑仍处于建筑当中，目前更新进度极慢。",
    "服务器地址：mc.kjchmc.cn": "服务器地址：mc.kjchmc.cn",
    "游戏版本：Java 1.16.5": "游戏版本：Java 1.16.5",
    "需下载特别制定版游戏客户端，客户端下载链接：": "需下载特别制定版游戏客户端，客户端下载链接：",
    "下载链接(点击前往)": "下载链接(点击前往)",
    "Site 站点": "Site 站点",
    "老况的文件库": "老况的文件库",
    "存储库": "存储库",
    "“一个存储着许多资料的站点”": "“一个存储着许多资料的站点”",
    "网站基于 Alist。涵盖了丰富资源，包括电子课本，番剧，Bilibili录播，实用电脑软件，壁纸，网站源码": "网站基于 Alist。涵盖了丰富资源，包括电子课本，番剧，Bilibili录播，实用电脑软件，壁纸，网站源码",
    "访问网站": "问网站",
    "老况的小窝": "老况的小窝",
    "“一个属于自己的博客”": "“一个属于自己的博客”",
    "学习繁忙，有可能经常断更文章。": "学习繁忙，有可能经常断更文章。",
    "kjch起始页": "kjch起始页",
    "起始页": "起始页",
    "设计": "设计",
    "前端": "前端",
    "“多功能起始页”": "“多功能起始页”",
    "内置多种壁纸以及多种可选的搜索引擎，美化了原先的浏览器内置标签页。": "内置多种壁纸以及多种可选的搜索引擎，美化了原先的浏览器内置标签页。",
    "网站状态监控": "网站状态监控",
    "服务器监控": "服务器监控",
    "“网站服务器在线状态检测站点”": "“网站服务器在线状态检测站点”",
    "CDN存储仓库": "v",
    "仓库": "仓库",
    "“小众的CDN加速服务”": "“小众的CDN加速服务”",
    "给网站提供文件加速服务，减轻站点服务器压力。": "给网站提供文件加速服务，减轻站点服务器压力。",
    "无前端显示界面，仅限于网站链接调用获取所需资源文件。": "无前端显示界面，仅限于网站链接调用获取所需资源文件。",
    "API主站点": "API主站点",
    "“为网站提供基础工具功能”": "“为网站提供基础工具功能”",
    "API主站点系统涵盖数十种维持网站正常运行的基本工具及资源。": "API主站点系统涵盖数十种维持网站正常运行的基本工具及资源。",
    "无前端显示页面，仅限于网站链接调用获取所需资源文件。": "无前端显示页面，仅限于网站链接调用获取所需资源文件。",
    "老k的主页": "老k的主页",
    "个人网站": "个人网站",
    "“网络世界上自己的小小一角。”": "“网络世界上自己的小小一角。”",
    "有一个属于自己的网站很酷，不是吗？": "有一个属于自己的网站很酷，不是吗？",
    "在互联网上有属于自己的小小一角是一件很有意义的事情，我是这么认为的。": "在互联网上有属于自己的小小一角是一件很有意义的事情，我是这么认为的。",
    "小玩意和开源工具": "小玩意和开源工具",
    "免费域名": "免费域名",
    "开源": "开源",
    "“为你有趣的开源项目提供免费子域名”": "“为你有趣的开源项目提供免费子域名”",
    "有一个酷酷的域名难道不是一个很有趣的事情吗?": "有一个酷酷的域名难道不是一个很有趣的事情吗?",
    "正如域名表达的内容一样，快来加入一起 “Make Some Cool” 吧！": "正如域名表达的内容一样，快来加入一起 “Make Some Cool” 吧！",
    "前往Github仓库": "前往Github仓库",
    "访客计数器": "访客计数器",
    "“记录网站访客数并实时显示”": "“记录网站访客数并实时显示”",
    "根据JS版修改并再创作而来。": "根据JS版修改并再创作而来。",
    "随机二次元图片": "随机二次元图片",
    "壁纸": "壁纸",
    "“随机展示一张二次元壁纸，可用作网站壁纸。”": "“随机展示一张二次元壁纸，可用作网站壁纸。”",
    "访问": "访问",
    "IP签名墙": "IP签名墙",
    "“快速生成一张带有浏览器、时间、访问IP信息的一张小图片”": "“快速生成一张带有浏览器、时间、访问IP信息的一张小图片”"
  }
}